#:schema node_modules/wrangler/config-schema.json
name = "fintraq-api"
main = "server/index.ts"
compatibility_date = "2024-08-06"

[[d1_databases]]
binding = "DB"
database_name = "fintraq"
database_id = "f13f6c83-be09-44d2-ae17-84ef940580bc"
